services:
  ssh:
    image: dev.unimake.remotes.ssh
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dev.unimake.remotes.ssh
    networks:
      unimake.ssh:
        ipv4_address: 171.16.14.2
    ports:
      - 22:22

networks:
  unimake.ssh:
    name: dev.unimake.remotes.ssh
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 171.16.14.0/24